name = "pgp-ranking"
main = "worker.js"
compatibility_date = "2026-05-01"

# `npx wrangler kv namespace create RANK` の出力で id を差し替える
[[kv_namespaces]]
binding = "RANK"
id = "650164c97c484bcb948f7e1a694f187f"
